import Head from "next/head";
import Image from "next/image";


import { useState } from 'react'

import { BsFacebook,BsInstagram,BsMailbox,BsPerson,BsTwitter } from 'react-icons/bs'
import { TbMessage } from 'react-icons/tb'
import { GiAutoRepair } from 'react-icons/gi'


export default function Home() {
  const [ name , setName] = useState<string>('')
  const [ email , setEmail] = useState<string>('')
  const [ message , setMessage] = useState<string>('')
  const [ subject , setSubject] = useState<string>('')

  return (
    <>
      <Head>
        <title>OnTheGo Mechanics </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hero min-h-screen relative">
        <div className="hero-overlay  bg-black bg-opacity-60 z-40 "></div>
          <Image alt="overlay-bg" fill src={"/1.jpg"} />
        <div className="hero-content text-center text-neutral-content z-50">
          <div className="max-w-lg">
            <h1 className="mb-5 text-5xl font-bold">OnTheGo Mechanics</h1>
            <p className="mb-5">
            When you are out on the road and your car decides to give up on you,
             it can be a frustrating and stressful experience. But with OnTheGo Mechanics,
              you can rest easy knowing that help is on the way.
            </p>
            <button className="btn btn-primary">Register Now</button>
          </div>
        </div>
      </div>
      <div className=" bg-accent flex justify-center">
        <div className=" container max-w-screen-xl my-10">
          <h2 className="text-primary text-3xl uppercase tracking-widest font-bold  my-6 ">Workshops</h2>
          <div className="flex gap-4 flex-wrap justify-around">
            <div className="card w-[calc(50%-1rem)] h-[30rem] bg-base-100 shadow-xl overflow-hidden">
              <figure><Image className="z-0" fill src="/7.webp" alt="Shoes" /></figure>
              <div className="h-full w-full absolute opacity-50 bg-black"/>
              <div className="flex h-full w-full z-50 justify-center items-center">
                <h2 className="card-title text-4xl">
                  Working Workshop
                </h2>
              </div>
            </div>
            <div className="card w-[calc(50%-1rem)] h-[30rem] bg-base-100 shadow-xl overflow-hidden">
              <figure><Image className="z-0" fill src="/8.jpg" alt="Shoes" /></figure>
              <div className="h-full w-full absolute opacity-50 bg-black"/>
              <div className="flex h-full w-full z-50 justify-center items-center">
                <h2 className="card-title text-4xl">
                  Cars Workshop
                </h2>
              </div>
            </div>
            <div className="card w-[calc(50%-1rem)] h-[30rem] bg-base-100 shadow-xl overflow-hidden">
              <figure><Image className="z-0" fill src="/9.jpg" alt="Shoes" /></figure>
              <div className="h-full w-full absolute opacity-50 bg-black"/>
              <div className="flex h-full w-full z-50 justify-center items-center">
                <h2 className="card-title text-4xl">
                  Storage Workshop
                </h2>
              </div>
            </div>
            <div className="card w-[calc(50%-1rem)] h-[30rem] bg-base-100 shadow-xl overflow-hidden">
              <figure><Image className="z-0" fill src="/0.jpeg" alt="Shoes" /></figure>
              <div className="h-full w-full absolute opacity-50 bg-black"/>
              <div className="flex h-full w-full z-50 justify-center items-center">
                <h2 className="card-title text-4xl">
                  primarytaince Workshop
                </h2>
              </div>
            </div>                        
          </div>
        </div>
      </div>
      <div className=" bg-primary flex justify-center">
        <div className=" container max-w-screen-xl my-10">
          <h2 className="text-accent text-3xl uppercase tracking-widest font-bold  my-6 ">About</h2>
          <div className="flex flex-wrap justify-around">
            <div className="w-1/3">
              <p>
              You may have a hot rod capable of going from 0 to 60 in less than five seconds, but if you continually push the engine, it will experience excessive wear and tear. You should also avoid start-and-stop driving, towing more than the vehicle’s recommended load, excessive speeding, and driving on dirt or gravel roads. Cautious driving keeps the engine in good shape and helps you avoid accidents, which is very important for primarytaining a vehicle’s value. Summer is the perfect time to have your car tuned up and prepped for a sale! To set up an appointment, please contact Mech Guy or call us at 021365489102.                
              </p>
            </div>
            <div className="w-2/3 relative">
              <Image fill alt="undraw" src={"/undraw.svg"} />
            </div>
          </div>
        </div>
      </div>   
      <div className=" bg-primary flex justify-center">
        <div className=" container max-w-screen-xl my-10">
          <h2 className="text-accent text-3xl uppercase tracking-widest font-bold  my-6 ">Team</h2>
          <div className="flex flex-wrap justify-around">
            <div className="w-1/4 px-2 ">
              <div className="h-80 relative rounded-lg overflow-hidden ">
                <Image fill className="object-cover"  alt="team" src={"/team1.jpg"} />
              </div>
              <div className="text-center mt-6">
                <h1 className="text-accent text-xl font-bold mb-1">
                    Saed Mohamed
                </h1>
                <div className="text-fuchsia-400 font-medium mb-2">
                  Founder & Specialist
                </div>
                <p className="text-secondary ">The big boss of the group who is love by everyone and does a great job on keeping everyone focus on their job.</p>
              </div>              
            </div>
            <div className="w-1/4 px-2 ">
              <div className="h-80 relative rounded-lg overflow-hidden ">
                <Image className="object-cover"  fill alt="team" src={"/team4.jpg"} />
              </div>
              <div className="text-center mt-6">
                <h1 className="text-accent text-xl font-bold mb-1">
                  Abdellah  Khaled
                </h1>
                <div className="text-fuchsia-400 font-medium mb-2">
                  Team Memeber
                </div>
                <p className="text-secondary ">The right man for the job always enjoys his work and finishs it on time.</p>
              </div>              
            </div>
            <div className="w-1/4 px-2 ">
              <div className="h-80 relative rounded-lg overflow-hidden ">
                <Image className="object-cover"  fill alt="team" src={"/team3.jpg"} />
              </div>
              <div className="text-center mt-6">
                <h1 className="text-accent text-xl font-bold mb-1">
                  Asmaa Abdelrahman
                </h1>
                <div className="text-fuchsia-400 font-medium mb-2">
                  Team Memeber
                </div>
                <p className="text-secondary ">A hard working member of the group don`t underastimate her just cause she is a woman she works harder then anyone.</p>
              </div>              
            </div>
            <div className="w-1/4 px-2 ">
              <div className="h-80 relative rounded-lg overflow-hidden ">
                <Image className="object-cover" fill alt="team" src={"/team2.jpg"} />
              </div>
              <div className="text-center mt-6">
                <h1 className="text-accent text-xl font-bold mb-1">
                    Mahmoud Ibrahim
                </h1>
                <div className="text-fuchsia-400 font-medium mb-2">
                  Team Memeber
                </div>
                <p className="text-secondary ">A big team worker works well with everyone to get the job well done.</p>
              </div>              
            </div>                                    
          </div>
        </div>
      </div> 
      <div className=" bg-accent flex justify-center">
        <div className="container max-w-screen-xl my-10">
          <h2 className="text-primary text-3xl uppercase tracking-widest font-bold  my-6 ">Contact</h2>
          <div className=' w-full px-4 flex flex-wrap '>
            <div className="form-control w-full ">
              <label className="label">
                <span className="label-text text-extraB">What is your name?</span>
              </label> 
              <div className='flex group'>
                <span className=' border-primary-content group-focus-within:bg-primary in-colors input input-bordered rounded-r-none flex justify-center items-center border-r-0'><BsPerson className=' text-primary transition-colors  duration-500 h-6 w-6 group-focus-within:text-accent' height={20} width={20} /></span>
                <input onChange={(e)=>setName(e.target.value)} value={name} type="text" placeholder="Name" className=" border-primary-content input input-bordered in-colors text-black focus:outline-0 w-full rounded-l-none pl-1 border-l-0"/>
              </div>
            </div> 
            <div className="form-control w-full ">
            <label className="label">
              <span className="label-text text-extraB">What is your email?</span>
            </label> 
            <div className='flex group'>
                <span className='group-focus-within:bg-primary in-colors input input-bordered  border-primary-content rounded-r-none flex justify-center items-center border-r-0'><BsMailbox className=' text-primary transition-colors  duration-500 h-6 w-6 group-focus-within:text-accent' height={20} width={20} /></span>
                <input onChange={(e)=>setEmail(e.target.value)} value={email}  type="email" placeholder="Email" className="input  border-primary-content input-bordered in-colors text-black focus:outline-0 w-full rounded-l-none pl-1 border-l-0"/>
              </div>
            </div> 
            <div className="form-control w-full ">
            <label className="label">
              <span className="label-text text-extraB">What is this about?</span>
            </label> 
            <div className='flex group'>
                <span className=' border-primary-content group-focus-within:bg-primary in-colors input input-bordered rounded-r-none flex justify-center items-center border-r-0'><BsMailbox className=' text-primary transition-colors  duration-500 h-6 w-6 group-focus-within:text-accent' height={20} width={20} /></span>
                <input onChange={(e)=>setSubject(e.target.value)} value={subject}  type="text" placeholder="Subject" className=" border-primary-content input input-bordered in-colors text-black focus:outline-0 w-full rounded-l-none pl-1 border-l-0"/>
              </div>
            </div>             
            <div className="form-control w-full">
              <label className="label">
                <span className="label-text text-extraB">What is your messsage?</span>
              </label> 
              <div className='flex group'>
                <span className='group-focus-within:bg-primary in-colors textarea textarea-bordered border-primary-content rounded-r-none flex justify-center items-center border-r-0'><TbMessage className=' text-primary transition-colors duration-500 h-6 w-6 group-focus-within:text-accent' height={20} width={20} /></span>
                <textarea  onChange={(e)=>setMessage(e.target.value)} value={message}  rows={3} placeholder="Message" className=" border-primary-content textarea in-colors textarea-bordered focus:outline-0 text-black w-full rounded-l-none pl-1 border-l-0"/>
              </div>
            </div>
            
            <button className="btn btn-primary p-4 px-10 mt-10">Send</button> 
          </div>
        </div>
      </div> 
      <footer className="footer items-center p-4 bg-primary text-neutral-content">
        <div className="items-center grid-flow-col">
          <GiAutoRepair className="text-5xl"/>
          <p>Copyright © 2023 - All right reserved</p>
        </div> 
        <div className="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
          <a><BsFacebook className="text-2xl" /></a> 
          <a><BsTwitter className="text-2xl" /></a> 
          <a><BsInstagram className="text-2xl" /></a> 

        </div>
      </footer>                        
    </>
  );
}
